//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksEntitiesDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute_Value
    {
        public int AvID { get; set; }
        public string AttValue { get; set; }
        public int AttributeID { get; set; }
    
        public virtual Attribute Attribute { get; set; }
    }
}
