//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksEntitiesDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Attribute_Book
    {
        public int ID { get; set; }
        public int BookID { get; set; }
        public int AttributeID { get; set; }

        public string ValueTypeText { get; set; }

        public DateTime? ValueTypeDate { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Book Book { get; set; }
    }
}
