//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksEntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Attribute_Book = new HashSet<Attribute_Book>();
            this.Book_Author = new HashSet<Book_Author>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public int AuthorID { get; set; }
        public int CountryID { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
        public Nullable<int> PagesCount { get; set; }
        public Nullable<int> ImageID { get; set; }
        public int AttributeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attribute_Book> Attribute_Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Author> Book_Author { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual Images Images { get; set; }
    }
}
